# Based on: https://vitejs.dev/guide/static-deploy.html
name: Publish to GitHub Pages
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allow manual invocations of this workflow

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        node-version: [20]
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build app with GitHub Pages base
        run: pnpm build -- --base /${{ github.event.repository.name }}
      - name: Configure Pages (if this fails, set Pages source to GitHub Actions in repo settings)
        uses: actions/configure-pages@v5
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist
          name: deployment
  deploy:
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      contents: write # To upload the deployment artifact to gh_pages branch
      pages: write # To deploy to Pages
      id-token: write # To verify the deployment originates from an appropriate source

    # Deploy to the GitHub pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Allow one concurrent deployment
    concurrency:
      group: ${{ github.workflow }}-deploy
    
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deployment
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
#      
#      
#      - name: Deploy pages artifact
#        uses: actions/deploy-pages@v4
#        id: deployment